[tool.bumpversion]
commit = true
tag = true
current_version = "0.0.0"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(\\-(?P<release>[a-z]+)\\.(?P<build>\\d+))?"
serialize = [
    "{major}.{minor}.{patch}-{release}.{build}",
    "{major}.{minor}.{patch}"
]

[tool.bumpversion.parts.release]
optional_value = "prod"
first_value = "dev"
values = [
	"dev",
	"rc",
    "prod"
]

[[tool.bumpversion.files]]
filename = "Dockerfile"